### ISSUE TITLE
FE_10_기본_세팅) 프로젝트 세팅 / 2h

### ISSUE THREAD

**Issue by kay0829** [kay0829/fe-sprint-coz-shopping#10]
프로젝트 세팅

- React
- 번들러: vite
  - [vite 설정 과정 및 공부 블로깅 링크 + 절대 경로](https://velog.io/@kay_/%EC%9D%B8%ED%84%B0%EB%A0%89%ED%8B%B0%EB%B8%8C-%EC%9B%B91-Vite%EC%99%80-%EC%A0%88%EB%8C%80%EA%B2%BD%EB%A1%9C)
- 언어: typescript
- css 라이브러리: tailwindcss
    - [tailwindcss 설정 과정 및 블로깅 링크](https://velog.io/@kay_/%EA%B5%AC%EA%B8%80-%EC%BA%98%EB%A6%B0%EB%8D%94-%ED%81%B4%EB%A1%A0%EC%BD%94%EB%94%A93-Tailwindcss)
- react-router-dom
- lint 설정: eslint 및 prettier

**Comment by dongyunkim96** [comment]
벌써 typescript로 작성하셔서 너무 부럽습니다. 프로젝트 세팅을 깔끔하게 하시고 시작하시는 것 보고 많이 배웁니다. 저도 앞으로 프로젝트 시작하기전에 세팅을 다 마쳐두고 시작해야겠어요. 끝까지 화이팅입니다!!
